services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network

  app:
    build: .
    container_name: bank_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_cards
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - bank_network

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge